/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Language } from './types';

export const TRANSLATIONS: Record<Language, any> = {
  en: {
    title: 'VoteWise',
    tagline: 'Empowering the Voter\'s Voice',
    description: 'A comprehensive platform to understand elections and access citizen services.',
    headline: "Empowering the Voter's Voice",
    startLearning: 'Start Learning',
    verifyStatus: 'Verify Voter Status',
    home: 'Home',
    services: 'Voter Services',
    education: 'Education',
    timeline: 'Timeline',
    aiAssistant: 'AI Assistant',
    boothFinder: 'Booth Finder',
    pasteAnalyze: 'Paste & Analyze',
    readiness: 'Voter Readiness',
    checksDone: 'checks completed',
    epicVerification: 'EPIC Verification',
    checkReg: 'Check Registration',
    directActions: 'Direct Actions',
    importantUpdate: 'Important Update',
    epiccDesc: 'Verify your registration status instantly using your Voter ID.',
    boothDesc: 'Find your assigned polling location and view real-time station capacity.',
    journeyTitle: 'Journey to the Booth',
    journeyDesc: 'Understand exactly what happens on the day you go to cast your vote.',
    startExplorer: 'Start Explorer',
    comingSoon: 'Coming Soon',
    notifications: 'Notifications',
    noNotifications: 'No new notifications.',
    editProfile: 'Edit Profile',
    saveProfile: 'Save Profile',
    verifiedVoter: 'Verified Voter',
    guestMode: 'Guest Mode',
    profile: 'User Profile',
    personalInfo: 'Personal Information',
    identityProof: 'Identity Proof',
    contactDetails: 'Contact Details',
    locationInfo: 'Location Details',
    nameLabel: 'Full Name',
    epicLabel: 'EPIC Number',
    aadhaarLabel: 'Aadhaar Number',
    phoneLabel: 'Phone Number',
    addressLabel: 'Current Address',
    photoLabel: 'Profile Photo',
    updateProfile: 'Update Profile',
    profileUpdated: 'Profile updated successfully!',
  },
  hi: {
    title: 'वोटवाइज',
    tagline: 'मतदाता की आवाज़ को सशक्त बनाना',
    description: 'चुनावों को समझने और नागरिक सेवाओं तक पहुँचने के लिए एक व्यापक मंच।',
    headline: "मतदाता की आवाज़ को सशक्त बनाना",
    startLearning: 'सीखना शुरू करें',
    verifyStatus: 'मतदाता स्थिति सत्यापित करें',
    home: 'होम',
    services: 'मतदाता सेवाएँ',
    education: 'शिक्षा',
    timeline: 'समयरेखा',
    aiAssistant: 'AI सहायक',
    boothFinder: 'बूथ खोजक',
    pasteAnalyze: 'पेस्ट और विश्लेषण',
    readiness: 'मतदाता तत्परता',
    checksDone: 'चेक पूरे हुए',
    epicVerification: 'EPIC सत्यापन',
    checkReg: 'पंजीकरण जांचें',
    directActions: 'सीधी कार्रवाइयां',
    importantUpdate: 'महत्वपूर्ण अपडेट',
    epiccDesc: 'अपनी मतदाता आईडी का उपयोग करके तुरंत अपनी पंजीकरण स्थिति सत्यापित करें।',
    boothDesc: 'अपना असाइन किया गया मतदान स्थान ढूंढें और वास्तविक समय की क्षमता देखें।',
    journeyTitle: 'बूथ तक की यात्रा',
    journeyDesc: 'सटीक रूप से समझें कि जिस दिन आप वोट डालने जाते हैं उस दिन क्या होता है।',
    startExplorer: 'एक्सप्लोरर शुरू करें',
    comingSoon: 'जल्द आ रहा है',
    notifications: 'सूचनाएं',
    noNotifications: 'कोई नई सूचना नहीं।',
    editProfile: 'प्रोफ़ाइल संपादित करें',
    saveProfile: 'प्रोफ़ाइल सहेजें',
    verifiedVoter: 'सत्यापित मतदाता',
    guestMode: 'अतिथि मोड',
    profile: 'उपयोगकर्ता प्रोफ़ाइल',
    personalInfo: 'व्यक्तिगत जानकारी',
    identityProof: 'पहचान प्रमाण',
    contactDetails: 'संपर्क विवरण',
    locationInfo: 'स्थान विवरण',
    nameLabel: 'पूरा नाम',
    epicLabel: 'EPIC नंबर',
    aadhaarLabel: 'आधार नंबर',
    phoneLabel: 'फ़ोन नंबर',
    addressLabel: 'वर्तमान पता',
    photoLabel: 'प्रोफ़ाइल फ़ोटो',
    updateProfile: 'प्रोफ़ाइल अपडेट करें',
    profileUpdated: 'प्रोफ़ाइल सफलतापूर्वक अपडेट की गई!',
  },
  ta: {
    title: 'வோட்வைஸ்',
    tagline: 'வாக்காளரின் குரலுக்கு அதிகாரம் அளித்தல்',
    description: 'தேர்தல்களைப் புரிந்துகொள்வதற்கும் குடிமக்கள் சேவைகளை அணுகுவதற்கும் ஒரு விரிவான தளம்.',
    headline: "வாக்காளரின் குரலுக்கு அதிகாரம் அளித்தல்",
    startLearning: 'கற்கத் தொடங்குங்கள்',
    verifyStatus: 'சரிபார்க்கவும்',
    home: 'முகப்பு',
    services: 'வாக்காளர் சேவைகள்',
    education: 'கல்வி',
    timeline: 'காலவரிசை',
    aiAssistant: 'AI உதவியாளர்',
    boothFinder: 'பூத் தேடுபவர்',
    pasteAnalyze: 'ஒட்டி பகுப்பாய்வு செய்',
    readiness: 'வாக்காளர் தயார்நிலை',
    checksDone: 'சோதனைகள் முடிக்கப்பட்டன',
    epicVerification: 'EPIC சரிபார்ப்பு',
    checkReg: 'பதிவைச் சரிபார்க்கவும்',
    directActions: 'நேரடி நடவடிக்கைகள்',
    importantUpdate: 'முக்கியமான மேம்படுத்தல்',
    epiccDesc: 'உங்கள் வாக்காளர் அடையாள அட்டையைப் பயன்படுத்தி உடனடியாக உங்கள் பதிவு நிலையைச் சரிபார்க்கவும்.',
    boothDesc: 'உங்களுக்கு ஒதுக்கப்பட்ட வாக்குச் சாவடியைக் கண்டறிந்து நேரலை நிலையைத் தெரிந்துக் கொள்ளுங்கள்.',
    journeyTitle: 'பூத் பயணம்',
    journeyDesc: 'வாக்களிக்கச் செல்லும் நாளில் சரியாக என்ன நடக்கும் என்பதைத் தெரிந்துக் கொள்ளுங்கள்.',
    startExplorer: 'தொடங்கவும்',
    comingSoon: 'விரைவில்',
    notifications: 'அறிவிப்புகள்',
    noNotifications: 'புதிய அறிவிப்புகள் இல்லை.',
    editProfile: 'விவரத்தைத் திருத்தவும்',
    saveProfile: 'சேமிக்கவும்',
    verifiedVoter: 'சரிபார்க்கப்பட்ட வாக்காளர்',
    guestMode: 'விருந்தினர் முறை',
    profile: 'சுயவிவரம்',
    personalInfo: 'தனிப்பட்ட தகவல்',
    identityProof: 'அடையாளச் சான்று',
    contactDetails: 'தொடர்பு விவரங்கள்',
    locationInfo: 'இருப்பிட விவரங்கள்',
    nameLabel: 'முழு பெயர்',
    epicLabel: 'EPIC எண்',
    aadhaarLabel: 'ஆதார் எண்',
    phoneLabel: 'தொலைபேசி எண்',
    addressLabel: 'தற்போதைய முகவரி',
    photoLabel: 'புகைப்படம்',
    updateProfile: 'புதுப்பிக்கவும்',
    profileUpdated: 'சுயவிவரம் வெற்றிகரமாக புதுப்பிக்கப்பட்டது!',
  }
};

export const EDUCATION_MODULES = [
  { 
    id: '1', 
    title: 'How to Vote', 
    desc: 'Step-by-step guide on what happens at the polling station.', 
    duration: '4 mins', 
    image: '/src/assets/images/regenerated_image_1777730090911.jpg',
    videoUrl: 'https://www.youtube.com/embed/YEu5Qv-VmRg'
  },
  { 
    id: '2', 
    title: 'EVM & VVPAT Guide', 
    desc: 'Learn how to use the Electronic Voting Machine correctly.', 
    duration: '3 mins', 
    image: '/src/assets/images/regenerated_image_1777730098331.png',
    videoUrl: 'https://www.youtube.com/embed/XGJQNKFYqYI'
  },
  { 
    id: '3', 
    title: 'Voter Awareness', 
    desc: 'Understanding your constitutional power as a citizen.', 
    duration: '5 mins', 
    image: '/src/assets/images/regenerated_image_1777730174153.jpg',
    videoUrl: 'https://www.youtube.com/embed/ytFYTVgJ5mc'
  },
];

export const INITIAL_TIMELINE = [
  { id: '1', title: 'Eligibility & Registration', description: 'Be an Indian citizen, 18+ years old, and register on the electoral roll.' },
  { id: '2', title: 'Election Announcement', description: 'ECI announces election dates and the Model Code of Conduct comes into force.' },
  { id: '3', title: 'Candidate Nomination', description: 'Candidates file their nominations and undergo scrutiny.' },
  { id: '4', title: 'Campaigning', description: 'Candidates and parties present their manifestos to the public.' },
  { id: '5', title: 'Silence Period', description: 'Campaigning stops 48 hours before the end of polling.' },
  { id: '6', title: 'Polling Day', description: 'Voters cast their votes at assigned polling stations using EVMs.' },
  { id: '7', title: 'Exit Polls', description: 'Surveys conducted immediately after voters leave polling stations.' },
  { id: '8', title: 'Counting of Votes', description: 'EVMs are opened and votes are counted in a secure environment.' },
  { id: '9', title: 'Results & Government Formation', description: 'Winners are declared and the government is formed based on majority.' },
];

export const READINESS_CHECKLIST = [
  { id: 'epic', label: 'Have EPIC card', description: 'Ensure you have your Voter ID card or an alternative identity proof.', completed: false },
  { id: 'booth', label: 'Know polling booth', description: 'Check your assigned polling station location in advance.', completed: false },
  { id: 'process', label: 'Understand voting process', description: 'Familiarize yourself with how to use EVM and VVPAT machines.', completed: false },
];

export const TN_CITIES = [
  'Chennai', 'Coimbatore', 'Madurai', 'Tiruchirappalli', 'Salem', 
  'Tirunelveli', 'Tiruppur', 'Vellore', 'Erode', 'Thoothukudi', 
  'Nagercoil', 'Thanjavur', 'Dindigul', 'Hosur', 'Sivakasi', 
  'Kanchipuram', 'Karur', 'Udhagamandalam (Ooty)', 'Ambur', 'Karaikudi', 
  'Neyveli', 'Kumbakonam', 'Nagapattinam', 'Pudukkottai', 'Rajapalayam', 
  'Gudiyatham', 'Pollachi', 'Vaniyambadi', 'Mayiladuthurai'
].sort();
